# Run using kubectl apply -f monogodb.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongo
        image: mongo:4.4
        ports:
        - containerPort: 27017

# go into mongodb
   
  ## get the pod name using           kubectl get pod -o wide

  ## go into the pod        kubectl exec -it <insert mongodb pod name here> -- sh

  ## go into the mongo db client    mongo mognodb://<ip address of mongo pod>:27017

  