{
 "title": "Kafka Consumer Dashboard",
 "tags": [
  "kafka",
  "consumer",
  "database",
  "MySQL",
  "MongoDB"
 ],
 "refresh": "auto",
 "panels": [
  {
   "title": "Kafka Consumer Service Reachability",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"kafka_consumer\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mongo Failure Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mongo_insert_failures_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Sensor Message Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "sensor_messages_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "MySQL Failure Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mysql_insert_failures_total", "legendFormat": "__auto" }
   ]
  }
 ]
}