{
 "title": "Log Producer Dashboard",
 "tags": [
  "sensor",
  "log"
 ],
 "refresh": "10s",
 "panels": [
  {
   "title": "Latest Log Type",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "latest_log_level" }
   ]
  },
  {
   "title": "Log Producer Service Reachability",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"log_producer\"}"
    }
   ]
  },
  {
   "title": "Log Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "log_level_events_total" }
   ]
  }
 ]
}