{
 "title": "Motion Sensor Dashboard",
 "tags": [
  "sensor",
  "motion"
 ],
 "refresh": "10s",
 "panels": [
  {
   "title": "Motion Sensor Service Reachability",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{job=\"motion_sensor\"}"
    }
   ]
  },
  {
   "title": "Total Motion Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    { "expr": "motion_messages_sent_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Motion Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    { "expr": "motion_events_detected_total", "legendFormat": "__auto" }
   ]
  }
 ]
}