{
 "title": "Temperature Sensor Dashboard",
 "tags": [
  "sensor",
  "temperature"
 ],
 "refresh": "10s",
 "panels": [
  {
   "title": "Temperature Reading ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "temperature_value_f", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Service Reachability",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{job=\"temperature_sensor\"}"
    }
   ]
  },
  {
   "title": "Temperature Messages Sent",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "temperature_messages_sent_total"
    }
   ]
  }
 ]
}