# humidity_sensor Service
apiVersion: v1
kind: Service
metadata:
  name: humidity-service
spec:
  selector:
    app: humidity
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
---
# humidity_sensor Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: humidity-sensor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: humidity
  template:
    metadata:
      labels:
        app: humidity
    spec:
      containers:
      - name: humidity
        image: your-dockerhub-username/humidity-sensor:latest
        imagePullPolicy: Always