# motion_sensor service
apiVersion: v1
kind: Service
metadata:
  name: motion-service
spec:
  selector:
    app: motion
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
---
# motion_sensor deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: motion-sensor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: motion
  template:
    metadata:
      labels:
        app: motion
    spec:
      containers:
      - name: motion
        image: motion_sensor:latest
        imagePullPolicy: Never
        ports:
          - containerPort: 8000
        env:
        - name: KAFKA_MOTION_ENABLED
          value: "true"
        - name: KAFKA_MOTION_TOPIC
          value: "sensor.motion"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka:9092"   # <--- Important: kafka hostname inside k8s cluster
        - name: METRICS_PORT
          value: "8000"