# temperature_sensor service
apiVersion: v1
kind: Service
metadata:
  name: temperature-service
spec:
  selector:
    app: temperature
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
---
# temperature_sensor deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: temperature-sensor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temperature
  template:
    metadata:
      labels:
        app: temperature
    spec:
      containers:
      - name: temperature
        image: your-dockerhub-username/temperature-sensor:latest
        imagePullPolicy: Always